# Generated by Django 3.0 on 2019-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=10)),
                ('Personal_Num1', models.CharField(max_length=13)),
                ('Personal_Num2', models.CharField(max_length=13)),
            ],
        ),
    ]
